import fs from 'fs';
import path from 'path';
import cloudinary from '../config/cloudinary.js';
import { runKagglePipeline } from '../../kaggle/kagglePipeline.js';
import congDongOnThiRepo from '../repository/congdongonthi.repo.js';


export async function uploadDocument(filePath, folder = 'documents') {
  const ext = path.extname(filePath).toLowerCase();
  const baseName = path.basename(filePath, ext);

  // Use 'auto' for images so Cloudinary registers them correctly under their native types,
  // and 'raw' for all documents (PDF, Word, Excel, PPT, MD) to avoid Cloudinary security blocking
  // and guarantee file opening.
  const isImage = ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg'].includes(ext);
  const resourceType = isImage ? 'auto' : 'raw';

  // Cloudinary's raw resource type does not automatically append file extensions,
  // so we must include it in the public_id.
  // For auto resource types (like images), Cloudinary automatically appends the
  // extension to the delivery URL, so we must omit it.
  const publicId = resourceType === 'raw'
    ? `${baseName}_${Date.now()}${ext}`
    : `${baseName}_${Date.now()}`;

  console.log(`[Upload Service] Uploading ${path.basename(filePath)} (type: ${resourceType}) to Cloudinary folder "${folder}"...`);

  const uploadResult = await cloudinary.uploader.upload(filePath, {
    resource_type: resourceType,
    folder: folder,
    public_id: publicId
  });

  console.log(`[Upload Service] Upload completed successfully. URL: ${uploadResult.secure_url}`);
  return uploadResult.secure_url;
}

/**
 * Extracts public_id and resource_type from a Cloudinary secure URL.
 */
export function parseCloudinaryUrl(url) {
  if (!url) return null;

  let resourceType = 'raw';
  if (url.includes('/image/upload/')) {
    resourceType = 'image';
  } else if (url.includes('/video/upload/')) {
    resourceType = 'video';
  }

  const regex = /\/upload\/(?:v\d+\/)?(.+)$/;
  const match = url.match(regex);
  if (match && match[1]) {
    let publicId = decodeURIComponent(match[1]);

    // For images/videos, Cloudinary's public_id excludes the extension, so strip it
    if (resourceType !== 'raw') {
      const extIndex = publicId.lastIndexOf('.');
      if (extIndex !== -1) {
        publicId = publicId.substring(0, extIndex);
      }
    }

    return { publicId, resourceType };
  }

  return null;
}

/**
 * Deletes an asset from Cloudinary by its URL.
 */
export async function deleteFromCloudinary(url) {
  const parsed = parseCloudinaryUrl(url);
  if (!parsed) return null;

  const { publicId, resourceType } = parsed;
  console.log(`[Cloudinary Service] Deleting public_id "${publicId}" (type: ${resourceType}) from Cloudinary...`);

  try {
    const result = await cloudinary.uploader.destroy(publicId, {
      resource_type: resourceType
    });
    console.log(`[Cloudinary Service] Delete result for "${publicId}":`, result);
    return result;
  } catch (error) {
    console.error(`[Cloudinary Service] Failed to delete public_id "${publicId}":`, error);
    return null;
  }
}

async function saveToDatabase(mdFiles, downloadUrl, metadata) {
  console.log(`[Database Service] Persisting ${mdFiles.length} Markdown document(s) to database...`);
  const savedDocs = [];

  if (metadata.level === 1) {
    await congDongOnThiRepo.resetHotDocuments();
  }

  for (const file of mdFiles) {
    const doc = await congDongOnThiRepo.create({
      subject: metadata.subject,
      title: metadata.title,
      description: metadata.description,
      level: metadata.level,
      downloads: 0,
      views: 0,
      fileType: metadata.fileType,
      fileSize: metadata.fileSize,
      tags: metadata.tags,
      mdDownloadUrl: file.content,
      downloadUrl: downloadUrl
    });
    savedDocs.push(doc);
  }

  return savedDocs;
}

export async function runPipeline(filePath, originalName, metadata) {
  const tempDownloadDir = path.resolve(process.cwd(), `temp_outputs_${Date.now()}`);

  try {
    const downloadUrl = await uploadDocument(filePath, 'documents');
    await runKagglePipeline(filePath, tempDownloadDir);
    const files = fs.readdirSync(tempDownloadDir);
    const mdFiles = [];

    for (const file of files) {
      if (file.endsWith('.md')) {
        const fullPath = path.join(tempDownloadDir, file);
        const mdUrl = await uploadDocument(fullPath, 'documents');

        mdFiles.push({
          fileName: file,
          content: mdUrl
        });
      }
    }

    if (mdFiles.length === 0) {
      throw new Error('No Markdown (.md) files were generated by the Kaggle Kernel.');
    }

    const results = await saveToDatabase(mdFiles, downloadUrl, metadata);

    return results;
  } finally {
    console.log('[Pipeline Service] Cleaning up temporary files...');
    if (fs.existsSync(tempDownloadDir)) {
      fs.rmSync(tempDownloadDir, { recursive: true, force: true });
    }
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
    console.log('[Pipeline Service] Cleanup finished.');
  }
}

/**
 * Fetches all documents ordered by creation date descending.
 */
export async function getAll() {
  return await congDongOnThiRepo.findAll();
}

/**
 * Fetches a single document by ID and increments the view count.
 */
export async function getById(id) {
  // Try incrementing views first
  try {
    await congDongOnThiRepo.update(id, {
      views: {
        increment: 1
      }
    });
  } catch (err) {
    console.error(`[Service] Failed to increment views for ${id}:`, err);
  }
  return await congDongOnThiRepo.findById(id);
}

/**
 * Updates basic text fields of a document (whitelist: subject, title, description, level, tags).
 */
export async function update(id, updateData) {
  const allowedFields = ['subject', 'title', 'description', 'level', 'tags'];
  const data = {};

  for (const field of allowedFields) {
    if (updateData[field] !== undefined) {
      if (field === 'level') {
        data[field] = parseInt(updateData[field], 10) === 1 ? 1 : 0;
      } else if (field === 'tags') {
        if (typeof updateData[field] === 'string') {
          try {
            data[field] = JSON.parse(updateData[field]);
          } catch {
            data[field] = updateData[field].split(',').map(t => t.trim()).filter(Boolean);
          }
        } else if (Array.isArray(updateData[field])) {
          data[field] = updateData[field];
        }
      } else {
        data[field] = updateData[field];
      }
    }
  }

  // Verify document exists
  const existing = await congDongOnThiRepo.findById(id);
  if (!existing) return null;

  if (data.level === 1) {
    await congDongOnThiRepo.resetHotDocuments();
  }

  return await congDongOnThiRepo.update(id, data);
}

/**
 * Deletes a document and its Cloudinary assets (with safety checks for shared original files).
 */
export async function deleteDoc(id) {
  const doc = await congDongOnThiRepo.findById(id);
  if (!doc) return null;

  // 1. Delete generated .md file from Cloudinary
  if (doc.mdDownloadUrl) {
    await deleteFromCloudinary(doc.mdDownloadUrl);
  }

  // 2. Delete original document from Cloudinary only if no other document record is using it
  if (doc.downloadUrl) {
    const otherDocsCount = await congDongOnThiRepo.countByDownloadUrlExceptId(doc.downloadUrl, doc.id);
    if (otherDocsCount === 0) {
      await deleteFromCloudinary(doc.downloadUrl);
    }
  }

  // 3. Delete database record
  return await congDongOnThiRepo.delete(id);
}

/**
 * Increments the downloads counter for a document.
 */
export async function incrementDownload(id) {
  const existing = await congDongOnThiRepo.findById(id);
  if (!existing) return null;

  return await congDongOnThiRepo.update(id, {
    downloads: {
      increment: 1
    }
  });
}

export async function getDistinctSubjects() {
  const records = await congDongOnThiRepo.findDistinctSubjects();
  return records.map(r => r.subject);
}

export default {
  uploadDocument,
  runPipeline,
  getAll,
  getById,
  update,
  deleteDoc,
  incrementDownload,
  getDistinctSubjects
};
